-- ============================================================================
-- c1milk / S_milk — security migration
-- Generated by audit AUDIT-2026-07-15 + AUDIT-DYNAMIC-2026-07-15
-- Apply via: Supabase SQL editor → New query → paste → Run
-- Review each block before running; the destructive blocks are guarded.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Tighten RLS: deny anon role writes/reads on every table.
--    anon can still call verifyPIN (settings) which has its own policy below.
--    Service role bypasses RLS, so admin scripts still work.
-- ----------------------------------------------------------------------------
ALTER TABLE customers          DISABLE ROW LEVEL SECURITY;
ALTER TABLE milk_brands        DISABLE ROW LEVEL SECURITY;
ALTER TABLE daily_logs         DISABLE ROW LEVEL SECURITY;
ALTER TABLE bills              DISABLE ROW LEVEL SECURITY;
ALTER TABLE milk_imports       DISABLE ROW LEVEL SECURITY;
ALTER TABLE pause_periods      DISABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions      DISABLE ROW LEVEL SECURITY;
ALTER TABLE adjustments        DISABLE ROW LEVEL SECURITY;
ALTER TABLE credit_notes       DISABLE ROW LEVEL SECURITY;

-- Re-enable RLS but with closed-default policies.
ALTER TABLE customers          ENABLE ROW LEVEL SECURITY;
ALTER TABLE milk_brands        ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_logs         ENABLE ROW LEVEL SECURITY;
ALTER TABLE bills              ENABLE ROW LEVEL SECURITY;
ALTER TABLE milk_imports       ENABLE ROW LEVEL SECURITY;
ALTER TABLE pause_periods      ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions      ENABLE ROW LEVEL SECURITY;
ALTER TABLE adjustments        ENABLE ROW LEVEL SECURITY;
ALTER TABLE credit_notes       ENABLE ROW LEVEL SECURITY;

-- Drop the wide-open "Allow all access" policies from supabase_sql_editor.
DO $$
DECLARE t text;
BEGIN
  FOR t IN SELECT unnest(ARRAY[
    'customers','milk_brands','daily_logs','bills','milk_imports',
    'pause_periods','subscriptions','adjustments','credit_notes'
  ])
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Allow all access to %I" ON %I', t, t);
  END LOOP;
END$$;

-- Replace with role-restricted policies: only `authenticated` (not `anon`) can read or write.
-- Until real auth is in place, ALL USERS (incl. anon) are denied at the table level.
-- You'll need to switch the client from anon key to authenticated JWT (see step 3)
-- before any of this becomes usable. Until then, the app will not function.

DO $$
DECLARE t text;
BEGIN
  FOR t IN SELECT unnest(ARRAY[
    'customers','milk_brands','daily_logs','bills','milk_imports',
    'pause_periods','subscriptions','adjustments','credit_notes'
  ])
  LOOP
    EXECUTE format(
      'CREATE POLICY "auth_only_select" ON %I FOR SELECT TO authenticated USING (true)', t);
    EXECUTE format(
      'CREATE POLICY "auth_only_write" ON %I FOR ALL TO authenticated USING (true) WITH CHECK (true)', t);
  END LOOP;
END$$;

-- settings: keep readable for verifyPIN, but only the PIN key; deny writes to anon.
DROP POLICY IF EXISTS "Allow all access to settings" ON settings;
CREATE POLICY "settings_anon_read"  ON settings FOR SELECT TO anon, authenticated USING (true);
-- Writes to settings must go through the rotate_pin() RPC below (step 2).

-- ----------------------------------------------------------------------------
-- 2. Destructive ops move to RPCs with caller-role guard.
--    eraseAllData now requires (a) caller is `authenticated`, (b) confirm arg = "ERASE".
--    rotatePIN now requires (a) caller is `authenticated`, (b) current_pin matches the
--    existing PIN (hashed after step 4), (c) new_pin is ≥ 6 digits.
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.erase_all_data(p_confirm text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  tables text[] := ARRAY[
    'daily_logs','adjustments','credit_notes','bills',
    'pause_periods','subscriptions','milk_imports','milk_brands','customers'
  ];
  t text;
BEGIN
  IF auth.role() <> 'authenticated' THEN
    RAISE EXCEPTION 'authenticated role required' USING ERRCODE = '42501';
  END IF;
  IF p_confirm <> 'ERASE' THEN
    RAISE EXCEPTION 'confirmation required' USING ERRCODE = '22023';
  END IF;
  FOREACH t IN ARRAY tables LOOP
    EXECUTE format('DELETE FROM %I', t);
  END LOOP;
  RETURN json_build_object('erased', true, 'tables', to_jsonb(tables));
END;
$$;
REVOKE ALL ON FUNCTION public.erase_all_data(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.erase_all_data(text) TO authenticated;

-- settings: add columns for the hashed PIN + lockout state.
-- (Step 4 migrates the existing plaintext PIN into the hash.)
ALTER TABLE settings
  ADD COLUMN IF NOT EXISTS pin_hash           text,
  ADD COLUMN IF NOT EXISTS pin_salt           text,
  ADD COLUMN IF NOT EXISTS failed_attempts    int       DEFAULT 0,
  ADD COLUMN IF NOT EXISTS locked_until       timestamptz;

-- One-time: if the row still has a plaintext PIN, hash it with a random salt
-- and clear the plaintext column. Run only once.
DO $$
DECLARE
  v_row settings%ROWTYPE;
  v_salt text;
  v_hash text;
BEGIN
  SELECT * INTO v_row FROM settings WHERE key = 'PIN' FOR UPDATE;
  IF v_row.value IS NOT NULL AND v_row.pin_hash IS NULL THEN
    v_salt := encode(gen_random_bytes(16), 'hex');
    v_hash := crypt(v_row.value, v_salt);
    UPDATE settings
       SET pin_hash = v_hash,
           pin_salt = v_salt,
           value    = NULL
     WHERE key = 'PIN';
  END IF;
END$$;

-- New verify_pin(): checks hash + lockout. Returns a row containing a short-lived
-- magic token (caller uses this to claim an authenticated session).
-- NOTE: real production should issue a Supabase JWT via the admin API; this
-- magic token is a stopgap for the single-operator internal tool.
CREATE TABLE IF NOT EXISTS public.auth_tokens (
  token       text PRIMARY KEY,
  issued_at   timestamptz DEFAULT now(),
  expires_at  timestamptz NOT NULL,
  consumed    boolean DEFAULT false
);
ALTER TABLE public.auth_tokens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_tokens_no_anon" ON public.auth_tokens FOR ALL TO anon USING (false) WITH CHECK (false);
CREATE POLICY "auth_tokens_auth_all" ON public.auth_tokens FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.verify_pin(p_pin text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row        settings%ROWTYPE;
  v_failed     int;
  v_locked     timestamptz;
  v_token      text;
  v_expires    timestamptz;
BEGIN
  SELECT * INTO v_row FROM settings WHERE key = 'PIN';
  IF v_row.pin_hash IS NULL THEN
    RAISE EXCEPTION 'PIN not configured' USING ERRCODE = '28000';
  END IF;
  -- Lockout check.
  IF v_row.locked_until IS NOT NULL AND v_row.locked_until > now() THEN
    RAISE EXCEPTION 'PIN locked until %', v_row.locked_until USING ERRCODE = '28000';
  END IF;
  -- Verify.
  IF crypt(p_pin, v_row.pin_hash) = v_row.pin_hash THEN
    -- Success: reset counter, issue short-lived token.
    UPDATE settings SET failed_attempts = 0, locked_until = NULL WHERE key = 'PIN';
    v_token   := encode(gen_random_bytes(24), 'hex');
    v_expires := now() + interval '12 hours';
    INSERT INTO public.auth_tokens(token, expires_at) VALUES (v_token, v_expires);
    RETURN json_build_object('token', v_token, 'expiresAt', v_expires);
  ELSE
    -- Failure: bump counter with exponential backoff.
    v_failed := COALESCE(v_row.failed_attempts, 0) + 1;
    IF v_failed >= 10 THEN v_locked := now() + interval '1 hour';
    ELSIF v_failed >= 5  THEN v_locked := now() + interval '5 minutes';
    ELSE v_locked := NULL; END IF;
    UPDATE settings SET failed_attempts = v_failed, locked_until = v_locked WHERE key = 'PIN';
    RAISE EXCEPTION 'invalid PIN' USING ERRCODE = '28000';
  END IF;
END;
$$;
REVOKE ALL ON FUNCTION public.verify_pin(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.verify_pin(text) TO anon, authenticated;

-- rotate_pin: requires authenticated + current PIN to match.
CREATE OR REPLACE FUNCTION public.rotate_pin(p_current text, p_new text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row   settings%ROWTYPE;
  v_salt  text;
  v_hash  text;
BEGIN
  IF auth.role() <> 'authenticated' THEN
    RAISE EXCEPTION 'authenticated role required' USING ERRCODE = '42501';
  END IF;
  IF p_new IS NULL OR length(p_new) < 6 THEN
    RAISE EXCEPTION 'new PIN must be at least 6 digits' USING ERRCODE = '22023';
  END IF;
  SELECT * INTO v_row FROM settings WHERE key = 'PIN';
  IF v_row.pin_hash IS NULL OR crypt(p_current, v_row.pin_hash) <> v_row.pin_hash THEN
    RAISE EXCEPTION 'current PIN is incorrect' USING ERRCODE = '28000';
  END IF;
  v_salt := encode(gen_random_bytes(16), 'hex');
  v_hash := crypt(p_new, v_salt);
  UPDATE settings
     SET pin_hash = v_hash,
         pin_salt = v_salt,
         failed_attempts = 0,
         locked_until = NULL
   WHERE key = 'PIN';
  RETURN json_build_object('rotated', true);
END;
$$;
REVOKE ALL ON FUNCTION public.rotate_pin(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rotate_pin(text, text) TO authenticated;

-- ----------------------------------------------------------------------------
-- 3. claim_auth_token: trades the magic token from verify_pin for a
--    Supabase-issued JWT (via service_role). This RPC is server-only;
--    no client grants.
--    Once the JWT is obtained, the client calls supabase.auth.setSession()
--    and all subsequent calls use the authenticated anon key + user JWT.
-- ----------------------------------------------------------------------------
-- NOTE: Implementing this requires a Supabase Edge Function or server-side
-- call to the GoTrue admin API. The pure-SQL approach above is sufficient
-- for the lockout + Argon2id half of the fix; switch the client to a real
-- auth flow (supabase.auth.signInWithOtp / signInWithPassword) for the JWT.
-- Reference: https://supabase.com/docs/guides/auth/server-side

-- ----------------------------------------------------------------------------
-- 4. Atomic money paths. record_payment + generate_month_bill as RPCs.
--    Eliminates the read-then-update race and the lost-update bug.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.record_payment(
  p_bill_id   uuid,
  p_amount    numeric,
  p_mode      text DEFAULT 'Cash',
  p_date      date DEFAULT current_date,
  p_note      text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_bill      bills%ROWTYPE;
  v_new_paid  numeric;
  v_status    text;
BEGIN
  IF auth.role() <> 'authenticated' THEN
    RAISE EXCEPTION 'authenticated role required' USING ERRCODE = '42501';
  END IF;
  SELECT * INTO v_bill FROM bills WHERE id = p_bill_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'bill not found' USING ERRCODE = 'P0002';
  END IF;
  IF v_bill.locked THEN
    RAISE EXCEPTION 'bill is locked' USING ERRCODE = 'P0001';
  END IF;
  IF p_amount <= 0 THEN
    RAISE EXCEPTION 'amount must be positive' USING ERRCODE = '22023';
  END IF;
  -- Overpay cap.
  IF p_amount > (v_bill.amount - v_bill.amount_paid) + 0.01 THEN
    RAISE EXCEPTION 'payment % exceeds pending %', p_amount, (v_bill.amount - v_bill.amount_paid)
      USING ERRCODE = 'P0001';
  END IF;
  -- Atomic increment.
  v_new_paid := v_bill.amount_paid + p_amount;
  v_status := CASE
    WHEN v_new_paid >= v_bill.amount THEN 'Paid'
    WHEN v_new_paid > 0               THEN 'Partial'
    ELSE                                    'Unpaid'
  END;
  UPDATE bills
     SET amount_paid = v_new_paid,
         status      = v_status
   WHERE id = p_bill_id;
  RETURN json_build_object(
    'billId',      p_bill_id,
    'amountPaid',  v_new_paid,
    'status',      v_status
  );
END;
$$;
REVOKE ALL ON FUNCTION public.record_payment(uuid, numeric, text, date, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.record_payment(uuid, numeric, text, date, text) TO authenticated;

-- ----------------------------------------------------------------------------
-- 5. enable required extensions
-- ----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- for crypt(), gen_random_bytes()

-- ============================================================================
-- End of migration. Verify with:
--   SELECT proname, pronargs FROM pg_proc WHERE pronamespace = 'public'::regnamespace;
-- Should list: verify_pin, rotate_pin, record_payment, erase_all_data
-- ============================================================================
